### ISSUE TITLE
TransitGateway is still created when "Use Existing One" is selected in the parameters.

### ISSUE THREAD

**Issue by tosmit** [fortinet/fortigate-autoscale-aws#14]
Guys first time posting something on Github but here goes.

I deployed the autoscale-tgw-new-vpc.template.yaml CF template Friday and found that when deploying "TransitGatewaySupportOptions" with a value of "use an existing one", a new TGW still gets created.  The logic is correct for all other functions so the attachments, associations, etc. all happen correctly but there is just a TGW that gets created a used for nothing.

After looking at the create-transit-gateway-components.template.yaml file it appears a condition needs to be added for the "TransitGateway" resource to only create the resource is "IfCreateTransitGateway" is true.  Should just be one additional line of code.

**Comment by JaydenLiang** [comment]
@tosmit we have already identified this issue as a known issue. Thank you for reporting.
