### ISSUE TITLE
Fortigate with GWLB

### ISSUE THREAD

**Issue by fawzihmouda** [fortinet/fortigate-autoscale-aws#16]
Hi, im currently testing the AWS new service Gateway Load Balancer (GWLB). When the GWLB autoscaling will be released. Is it possible to use autoscaling without TGW in my case ? And is there any extra configuration on the fortigatte to support GWLB with GENEVIE tunnel. Thanks :)

**Comment by JaydenLiang** [comment]
Hi @fawzihmouda , please send your inquiry to github@fortinet.com.
